/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FFT */

#ifndef _Included_FFT
#define _Included_FFT
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FFT
 * Method:    nfft
 * Signature: ([D[D[D[D)V
 */
JNIEXPORT void JNICALL Java_FFT_nfft
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     FFT
 * Method:    nifft
 * Signature: ([D[D[D[D)V
 */
JNIEXPORT void JNICALL Java_FFT_nifft
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
