/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Nblint */

#ifndef _Included_Nblint
#define _Included_Nblint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Nblint
 * Method:    native_nblint
 * Signature: ([S[S)V
 */
JNIEXPORT void JNICALL Java_Nblint_native_1nblint
  (JNIEnv *, jclass, jshortArray, jshortArray);

/*
 * Class:     Nblint
 * Method:    native_nshint
 * Signature: ([S[S)V
 */
JNIEXPORT void JNICALL Java_Nblint_native_1nshint
  (JNIEnv *, jclass, jshortArray, jshortArray);

#ifdef __cplusplus
}
#endif
#endif
